/*:

# The Swift Programming Langauge (6)

 * [Basics](2.Basics)
 * [Basic Operators](3.BasicOperators)
 * [Strings And Characters](4.StringsAndCharacters)
 * [Collection Types](5.CollectionTypes)
 * [Control Flow](6.ControlFlow)
 * [Functions](7.Functions)
 * [Closure](8.Closure)
 * [Enumeration](9.Enumeration)
 * [Structure And Classes](10.StructureAndClasses)
 * [Properties](11.Properties)
 * [Subscripts](12.Subscripts)
 * [Inheritance](13.Inheritance)
 * [Initialization](14.Initialization)
 * [Deinitialization](15.Deinitialization)
 * [Optional Chaining](16.OptionalChaining)
 * [Error Handling](17.ErrorHandling)
 * [Concurrency](18.Concurrency)
 * [Macros](19.Macros)
 * [TypeCasting](20.TypeCasting)
 * [NestedTypes](21.NestedTypes)
 * [Extensions](22.Extensions)
 * [Protocols](23.Protocols)
 * [Generics](24.Generics)
 * [Opaque and Boxed Protocol Types](25.OpaqueAndBoxedProtocolTypes)
 * [Automatic Reference Counting](26.AutomaticReferenceCounting)
 * [Access Control](27.AccessControl)
 * [Advanced Operators](28.AdvancedOperators)

*/

//: [Next Topic](@next)
